### ISSUE TITLE
Reconsider gutter background

### ISSUE THREAD

**Issue by cideM** [harg/iceberg-visual-studio-code#1]
Iceberg is one of my favorite themes and I use it for both neovim and iterm. In Visual Studio Code however the very prominent gutter keeps me from using it. Of course, colors are subjective, but in my humble opinion, giving the gutter a background color other than the editor background is a really drastic move, mostly for centered editor layout (see screenshot). There's the option of overriding colors, but I think that the theme would just look a lot better if the gutter, per default, had the editor background as well.
<img width="1680" alt="screen shot 2018-10-15 at 16 27 15" src="https://user-images.githubusercontent.com/4246921/46957251-77011980-d097-11e8-8235-930390d6c782.png">

**Comment by harg** [comment]
Fixed in 1.2.0
