### ISSUE TITLE
Flags in CLI commands are near invisible

### ISSUE THREAD

**Issue by awulkan** [harg/iceberg-visual-studio-code#2]
Hey there. I love the theme, but I have one issue. When I enter a CLI command with a flag, the flag is almost invisible.

As you can see in the below image, I'm running this command `hugo server -D`, but the `-D` is so dark you can barely see it.

![image](https://i.imgur.com/utAQI0n.png)

**Comment by harg** [comment]
What shell are you using?

**Comment by awulkan** [comment]
Powershell

**Comment by awulkan** [comment]
Same problems with Bash by the way.

**Comment by harg** [comment]
Fixed in 1.2.0

**Comment by awulkan** [comment]
Thank you, much appreciated.
